using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Pickable : MonoBehaviour
{
    public int scoreAmount = 2;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    // aþaðýdaki metod objenin is trigger  bir girdi bir dönüþ saðlýyor
    // objenin isTrigger seçöeneði seçili, tikli ise,other is trigger'ýn içinden geçen objeyi dönüyor. (yani playera ulaþýcaz)  */
    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.tag == "Player")
        {
            ScoreManager scoreManager = FindObjectOfType<ScoreManager>(); //score manager'ý referans aldýk.
            scoreManager.score += scoreAmount;
            Destroy(gameObject); // buradaki game object bu scripptin takýlý olduðu game object
        }
       
    }

    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.tag == "Player")
        {
            ScoreManager scoreManager = FindObjectOfType<ScoreManager>(); //score manager'ý referans aldýk.
            scoreManager.score += scoreAmount;
            Destroy(gameObject); // buradaki game object bu scripptin takýlý olduðu game object
        }

    }
}
